apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app
  namespace: plutus
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: registry.pettitservers.com:5000/plutus/plutus-app:{{ .Values.imageTag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8043
              name: https
      imagePullSecrets:
        - name: regcred
