apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: plutus
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8043
      targetPort: 8043
      name: https
